name: Triboneira
description: App para galera da tribo gaules.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  carousel_slider: ^2.2.1
  material_design_icons_flutter: ^4.0.5555
  shared_preferences: ^0.5.10
  cached_network_image: ^2.3.1
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  flutter_modular: ^2.0.0+1
  flutter_web_auth:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/icon/
    - assets/fonts/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  
  fonts:
    - family: Draft B
      fonts:
        - asset: assets/fonts/DraftB_Regular.otf
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
    - family: GoogleSansBold
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf

  flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icon/app-icon.png"
  image_path_ios: "assets/images/icon/app-icon-ios.png"
  adaptive_icon_background: "assets/images/icon/background.png" #"#ffffff" #backgroundColor/ImagePath
  adaptive_icon_foreground: "assets/images/icon/foreground.png"

vars:
  runner: flutter pub run build_runner
  clean: flutter clean
  get: flutter pub get
scripts:
  build: $runner build --delete-conflicting-outputs
  mobx: $runner watch --delete-conflicting-outputs
  watch: $clean & $get & $runner watch --delete-conflicting-outputs
  clean: $clean & $get & $runner clean  
  icons: $get & flutter pub run flutter_launcher_icons:main